# Generated by Django 3.2.8 on 2021-10-24 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('recipe', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailedRecipe',
            fields=[
                ('origin_id', models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipe.recipe')),
                ('ingredients_list', models.TextField()),
                ('calories', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedRecipeCalorieContributions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient', models.TextField()),
                ('calories', models.IntegerField()),
                ('parent_recipe_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
